feature -generateTestSources changed to generate sources to different directory (out of harness directory structure)
svn path=/trunk/; revision=646

diff --git a/test-harness/core/src/main/resources/com/sun/xml/ws/test/freemarker/client b/test-harness/core/src/main/resources/com/sun/xml/ws/test/freemarker/client
--- a/test-harness/core/src/main/resources/com/sun/xml/ws/test/freemarker/client
+++ b/test-harness/core/src/main/resources/com/sun/xml/ws/test/freemarker/client
@@ -3,8 +3,45 @@
 # stage: ${stage}
 export CTX=${serviceId}:${stage}-client
 
+if [ "$debug" = "true" ]; then
+   echo == $CTX ========================================================
+fi;
+
+function r {
+    if [ $G_STATUS -ne 0 ]; then
+        return $G_STATUS;
+    fi;
+    if [ "$debug" = "true" ]; then
+       #echo $CTX: $G_STATUS
+       echo "$@"
+       echo ""
+       "$@"
+    else
+       echo "$@" >> log.txt 2>&1
+       echo "" >> log.txt 2>&1
+       "$@" >> log.txt 2>&1
+    fi;
+
+    local status=$?
+    if [ $status -ne 0 ]; then
+        G_STATUS=$status
+        FAILED=$((FAILED+1))
+        echo "FAILED: $CTX/$1"
+        echo "FAILED: $CTX/$1" >> log.txt 2>&1
+    fi
+    return $status
+}
+
 r echo "Running ${testName}"
-r javac -cp ${classpath} bsh/Client${stage}.java
+
+SRC_FILES=
+if [ -d "client-source" ]; then
+    SRC_FILES=`find client-source -name '*.java'`
+    r javac -cp ${classpath} -d client-classes $SRC_FILES
+fi
+
+r javac -cp ${classpath} -d client-classes \
+     bsh/Client${stage}.java
 
 if [ "$skipTests" != "true" ]; then 
   r java -cp ${classpath} bsh.Client${stage}
diff --git a/test-harness/core/src/main/resources/com/sun/xml/ws/test/freemarker/deploy b/test-harness/core/src/main/resources/com/sun/xml/ws/test/freemarker/deploy
--- a/test-harness/core/src/main/resources/com/sun/xml/ws/test/freemarker/deploy
+++ b/test-harness/core/src/main/resources/com/sun/xml/ws/test/freemarker/deploy
@@ -3,6 +3,39 @@
 # stage: ${stage}
 export CTX=${serviceId}:${stage}-deploy
 
+if [ "$debug" = "true" ]; then
+   echo == $CTX ========================================================
+fi;
+
+function r {
+    if [ $G_STATUS -ne 0 ]; then
+        return $G_STATUS;
+    fi;
+    if [ "$debug" = "true" ]; then
+       #echo $CTX: $G_STATUS
+       echo "$@"
+       echo ""
+       "$@"
+    else
+       echo "$@" >> log.txt 2>&1
+       echo "" >> log.txt 2>&1
+       "$@" >> log.txt 2>&1
+    fi;
+
+    local status=$?
+    if [ $status -ne 0 ]; then
+        G_STATUS=$status
+        FAILED=$((FAILED+1))
+        echo "FAILED: $CTX/$1"
+    fi
+    return $status
+}
+
+# copy wsdls ...
+mkdir -p services/server/war/WEB-INF/wsdl/ > /dev/null 2>&1 | true
+cp ../src/server/*.wsdl services/server/war/WEB-INF/wsdl/ > /dev/null 2>&1 | true
+cp ../src/server/*.xsd services/server/war/WEB-INF/wsdl/ > /dev/null 2>&1 | true
+
 r javac -cp ${classpath} bsh/Deploy${stage}.java
 
 if [ $G_STATUS -ne 0 ]; then
diff --git a/test-harness/core/src/main/resources/com/sun/xml/ws/test/freemarker/tool b/test-harness/core/src/main/resources/com/sun/xml/ws/test/freemarker/tool
--- a/test-harness/core/src/main/resources/com/sun/xml/ws/test/freemarker/tool
+++ b/test-harness/core/src/main/resources/com/sun/xml/ws/test/freemarker/tool
@@ -3,10 +3,38 @@
 # stage: ${stage}
 export CTX=${serviceId}:${stage}-tool
 
+if [ "$debug" = "true" ]; then
+   echo == $CTX ========================================================
+fi;
+
+function r {
+    if [ $G_STATUS -ne 0 ]; then
+        return $G_STATUS;
+    fi;
+    if [ "$debug" = "true" ]; then
+       #echo $CTX: $G_STATUS
+       echo "$@"
+       echo ""
+       "$@"
+    else
+       echo "$@" >> log.txt 2>&1
+       echo "" >> log.txt 2>&1
+       "$@" >> log.txt 2>&1
+    fi;
+
+    local status=$?
+    if [ $status -ne 0 ]; then
+        G_STATUS=$status
+        FAILED=$((FAILED+1))
+        echo "FAILED: $CTX/$1"
+    fi
+    return $status
+}
+
 <#list dirs as dir>
 r mkdir -p ${dir}
 </#list>
 
-r <#list params as param>${param} <#if param_has_next>\</#if>
+r <#list params as param>      ${param} <#if param_has_next>\</#if>
 </#list>
 
